### PR TITLE
370 lx im getting spammed by feedback requests every few seconds even after checking dont show this again

### LINKED ISSUE #370: [LX] I'm getting spammed by feedback requests every few seconds, even after checking "Don't show this again"
**Describe the bug**
See title.
It feels very unprofessional and breaks trust with the user since we effectively ignore their request to stop showing it.
Looking at the code in FeedbackPopUp, there are some obvious code bugs related to timeouts not being cancelled which slipped through.

**To Reproduce**

Can't think of exactly what steps are needed but just use LX for a period of time, it happens to me often.

**Expected behaviour**
The window should only appear every so often (I'd say 5 mins after opening the app then every 30 mins).
And we should respect the user's request if they dismiss it.
The options are also confusing. After ticking 'don't show this again', I think 'Maybe Later' should change to 'Close'

### PR DESCRIPTION
**Pull request by ms0ur1s**
### What? Why?
The previous feedback pop-up implementation was buggy with users being increasingly spammed by the pop-up. This iteration takes the back-end updates introduced [here](https://github.com/DigitalCommons/land-explorer-back-end/pull/69), that added an `ask_for_feedback` column to the `user` table, and updates / sets the redux state based on the db value, instead of local storage.

Relates to #370 
In conjunction with PR [#69](https://github.com/DigitalCommons/land-explorer-back-end/pull/69)

#### New functionality for managing feedback preferences:
* [`src/actions/UserActions.js`](diffhunk://#diff-0947d6ee4a669d435cf3e4ecee5bd5619232c4a139096606210837c3f1c37889L1-R38): Added `getAskForFeedback` and `setAskForFeedback` actions to fetch and update the user's feedback preference using API endpoints.

#### Updates to the `FeedbackPopUp` component:
* [`src/components/modals/FeedbackPopUp.js`](diffhunk://#diff-3ec2af614d62057e76f3cc83cf80a95cae8aff17eb44bb7015f2a7a19586d70cR6-L15): Replaced local storage usage with Redux state for managing the feedback preference (`askForFeedback`). The component now dispatches `setAskForFeedback` to update the preference and uses the Redux selector `state.user.askForFeedback` to determine the current status. [[1]](diffhunk://#diff-3ec2af614d62057e76f3cc83cf80a95cae8aff17eb44bb7015f2a7a19586d70cR6-L15) [[2]](diffhunk://#diff-3ec2af614d62057e76f3cc83cf80a95cae8aff17eb44bb7015f2a7a19586d70cL28-R38) [[3]](diffhunk://#diff-3ec2af614d62057e76f3cc83cf80a95cae8aff17eb44bb7015f2a7a19586d70cL49-L68) [[4]](diffhunk://#diff-3ec2af614d62057e76f3cc83cf80a95cae8aff17eb44bb7015f2a7a19586d70cL96-R91)

#### Integration with the application lifecycle:
* [`src/pages/MapApp.js`](diffhunk://#diff-ce45bb72adbba36f8726db35dd5e76a87774162e3dcb090f1f588bb4943d9061L11-R11): Added a call to `getAskForFeedback` during the app initialization process to ensure the feedback preference is loaded when the user logs in. [[1]](diffhunk://#diff-ce45bb72adbba36f8726db35dd5e76a87774162e3dcb090f1f588bb4943d9061L11-R11) [[2]](diffhunk://#diff-ce45bb72adbba36f8726db35dd5e76a87774162e3dcb090f1f588bb4943d9061R32)

#### State management updates:
* [`src/reducers/UserReducer.js`](diffhunk://#diff-8cd9aae5b0eca01b2fd28c2fecbc26aaea8ece0314e2395769aec14d94caa416R22): Updated the initial state to include `askForFeedback` (defaulting to `true`) and added a new case in the reducer to handle the `USER_FEEDBACK_STATUS` action for updating the state. [[1]](diffhunk://#diff-8cd9aae5b0eca01b2fd28c2fecbc26aaea8ece0314e2395769aec14d94caa416R22) [[2]](diffhunk://#diff-8cd9aae5b0eca01b2fd28c2fecbc26aaea8ece0314e2395769aec14d94caa416R37-R41)

### Release notes

Requires the merging of PR [#69](https://github.com/DigitalCommons/land-explorer-back-end/pull/69) and a `user` table update before testing is possible

### What should we test?
- Toggle on a Land Ownership layer and ensure it takes 5 mins for the pop-up to appear
- Move you mouse up the address bar to activate the pop-up
- Click the 'Don't show this again' checkbox
- Close the pop-up
- Move you mouse up the address bar and ensure the pop-up does not appear
- Repeat step 1 ensuring no pop-up appears

### CODE REVIEW

**Review by King-Mob — APPROVED** [review]

File: src/components/modals/FeedbackPopUp.js [hunk 1]
```diff
@@ -46,26 +47,20 @@ const FeedbackPopUp = () => {
...
-    return feedbackModalPreference === "false";
-  };
+  }, [feedbackPreference]);
 
   // Show modal after delay if property layer is active
   useEffect(() => {
-    if (propertyLayerActive) {
-      setAskForFeedback(true);
-      setTimeout(() => {
+    let timeoutId;
```
Comment (rogup) [inline src/components/modals/FeedbackPopUp.js:54]: Are we sure this works in testing?
I would have thought timeoutId as a variable doesn't persist outside this block, so the clearTimeout doesn't have any effect and won't cancel previous timers.

I think there needs to be a variable outside the useEffect() block. And it probably needs to use useRef() so that it persists between React renders.

Comment (lin-d-hop) [reply src/components/modals/FeedbackPopUp.js:54]: I think @rogup is right about this. I have created a new account and used for 10 mins and have not seen the pop up come up. Seems like a bug.

Comment (rogup) [reply src/components/modals/FeedbackPopUp.js:54]: @lin-d-hop I think that it's not showing at all for you since https://github.com/DigitalCommons/land-explorer-front-end/commit/28a5b22109e76611deba675885261ac2dc202339 has not been reverted.
I've just done this now. I expect you'll now get spammed with lots of popups if you make lots of changes to the property layer display, due to this bug
