### PR TITLE
Ownership Search - highlighting fix for selected properties

### LINKED ISSUE #311: Ownership Search: Related properties not highlighting on map
**Describe the bug**
When using the ownership search to see related properties, the properties aren't highlighting on the map. And clicking on one property selects all of them.

**To Reproduce**
1. Turn on ownership search
2. Select green property
3. Click 'check for other properties'
4. Click arrow next to one of the properties
5. Click clear all, then click one of the properties in the list

**Expected behaviour**

1. The properties highlighted in green should display on the map
2. The properties should only be highlighted in green if they have been clicked on

**Screenshots/GIFs**
lx bug property selection

**Context (please complete the following information):**
 - Device: desktop
 - OS: windows 10
 - Browser: chrome
 - Version: 123

**Additional context**
I checked to see if this was happening on my local version of the front-end. I haven't pulled from dev since I left the project. Connecting my local version to the staging back-end, this bug doesn't appear.

### PR DESCRIPTION
**Pull request by ms0ur1s**
#### What? Why?

Currently, when an arrow next to a property within the 'Ownership Search' panel is clicked, the property is not highlighted in red on the map.

Closes #311

After investigation the `handlePropertyClick` function only needed to be be added to the `gotoProperty` function within `RelatedProperties.js`.

I was unable to reproduce the second bug mentioned in issue #311 locally, on staging or on live (click 'clear all' within the 'Ownership Search' panel, click another property within this panel and all properties listed in the panel are highlighted green).

#### What should we test?

1. Turn on ownership search
2. Zoom in and click on a green poly
3. Open the 'Land Information' panel and click 'Check for other properties'
4. Click an arrow to the right of a property within the 'Ownership Search' panel

### CODE REVIEW

File: src/components/left-pane/RelatedProperties.js [hunk 1]
```diff
@@ -21,39 +21,45 @@ const RelatedProperties = ({ property }) => {
 
   const gotoProperty = () => {
     dispatch(setLngLat(lng, lat));
+    handlePropertyClick();
```
Comment (rogup) [inline src/components/left-pane/RelatedProperties.js:24]: `handlePropertyClick()` toggles the highlighting of a property. I think in this scenario, we want to always highlight it.
So I think it makes sense for this line to be `dispatch(selectRelatedProperties({ [property.poly_id]: property }));` instead

**Review by rogup — COMMENTED** [review]
@ms0ur1s Looks good! Just one minor suggestion

File: src/components/left-pane/RelatedProperties.js (hunk 1 above)
Comment (ms0ur1s) [reply src/components/left-pane/RelatedProperties.js]: Thanks for the knowledge, man. All sorted.
