### PR TITLE
Bug fix: Close button on polygons should close the popup

### LINKED ISSUE #180: 'x' doesn't work to close pop-up on polygon
**Describe the bug**
Clicking 'x' doesn't work to close pop-up on polygon

**To Reproduce**
1. Create a polygon
2. Open the description
3. Click 'x'
4. See the popup doesnt close

**Expected behaviour**
Clicking 'x' closes pop-up on polygon

**Screenshots/GIFs**
Screenshot from 2023-01-24 03-20-56

**Context (please complete the following information):**
 Production on PC, Linux, Firefox/Chrome

**Additional context**

### PR DESCRIPTION
**Pull request by King-Mob**
#### What? Why?

Closes #180

Removed an on click method on the marker that was keeping the popup open. 

#### What should we test?

Draw polygon, click on it, click on the x to close it

#### Deployment notes

none

### CODE REVIEW

File: src/components/Drawing.js [hunk 1]
```diff
@@ -1,118 +1,93 @@
...
+const Drawing = ({ type, polygon }) => {
+    const [popupClosed, setPopupClosed] = useState(false);
+    const activeTool = useSelector(state => state.navigation.activeTool);
+    const activePolygon = useSelector(state => state.drawings.activePolygon);
+    const baseLayer = useSelector(state => state.mapBaseLayer.layer);
 
-    componentDidUpdate(prevProps) {
-        let uuid = this.props.polygon.uuid;
-        if ((prevProps.activePolygon === uuid) && (this.props.activePolygon !== uuid)) {
-            this.setState({ popupClosed: false });
```
Comment (rogup) [inline src/components/Drawing.js:20]: I added this logic earlier so that the popup would show if the user selects an object from the 'Info' pane, if the popup was previously closed. I'm not sure how to achieve the same with functional components and useEffect(). I don't know how much of an edge case it is, since we don't know how often people use the Info pane. I'm guessing maybe people use it a fair bit if they have lots of drawings?

Comment (King-Mob) [reply src/components/Drawing.js:20]: Thanks, I've added a useEffect to keep this fix.

**Comment by lin-d-hop** [comment]
Thanks for this fix :+1:
